Revert "Add f16/f128 handling in a couple places"
The f16/f128 handling introduced as part of rust-lang/rustc#125016 (Update
compiler_builtins to 0.1.114) broke compilation on LoongArch and RISC-V:

error: internal compiler error: compiler/rustc_codegen_llvm/src/abi.rs:
126:22: unsupported float: Reg { kind: Float, size: Size(2 bytes) }

thread 'rustc' panicked at compiler/rustc_codegen_llvm/src/abi.rs:126:22:
Box<dyn Any>

This should be resolved with LLVM 19, but we are still on LLVM 18.

Revert 99e6a28804eac57faa37134d61a2bb17069996a2 as a temporary workaround.

Ref: https://github.com/rust-lang/rust/pull/125016